### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by stuartaccent** [accent-starlette/starlette-admin#4]
- [x] Header page needs logout url and proper user.display_name
- [x] Permission Scopes
- [x] Return instance in `do_create`, `do_update`
- [ ] Design a home screen
- [ ] Create a section view that lists the admins in that section
- [ ] Hide links in sidebar that a user doesn't have access to
- [ ] Tests
- [ ] Docs
